import type { NeuralCoreOperationalExecution } from "../domain/neural-core-operational-execution.types";
import { normalizeNeuralCoreOperationalExecution } from "../mappers/neural-core-operational-scenario.mapper";
import {
  NEURAL_CORE_OPERATIONAL_CLUSTER_IDS as CLUSTER,
  NEURAL_CORE_OPERATIONAL_ROUTE_IDS as ROUTE,
  NEURAL_CORE_OPERATIONAL_STAGE_IDS as STAGE,
} from "../mappers/neural-core-operational-topology.mapper";

export const NEURAL_CORE_OPERATIONAL_RECOVERY_EXECUTION_ID = "execution:request-recovery";

export const NEURAL_CORE_OPERATIONAL_RECOVERY_EXECUTION:
NeuralCoreOperationalExecution = normalizeNeuralCoreOperationalExecution({
  id: NEURAL_CORE_OPERATIONAL_RECOVERY_EXECUTION_ID,
  name: "Failure and Recovery",
  shortName: "Recovery",
  kind: "failure-recovery",
  description: "Localized external timeout recovers through one explicitly scheduled retry.",
  events: [
    { id: "recovery:001:execution-started", type: "execution-started", status: "processing", atMs: 0, durationMs: 0, title: "Execution started", metadata: { correlationId: "req-recovery-001" } },
    { id: "recovery:002:request-received", type: "request-received", status: "processing", atMs: 4, durationMs: 0, stageId: STAGE.clientRequest, clusterId: CLUSTER.clientRequest, title: "Client request received" },
    { id: "recovery:003:client-entered", type: "stage-entered", status: "processing", atMs: 5, durationMs: 3, stageId: STAGE.clientRequest, clusterId: CLUSTER.clientRequest, title: "Request accepted" },
    { id: "recovery:004:client-completed", type: "stage-completed", status: "success", atMs: 8, durationMs: 0, stageId: STAGE.clientRequest, clusterId: CLUSTER.clientRequest, title: "Request prepared" },
    { id: "recovery:005:route-gateway", type: "route-transmission", status: "processing", atMs: 10, durationMs: 2, routeId: ROUTE.clientToGateway, title: "Request transmitted to gateway" },
    { id: "recovery:006:gateway-entered", type: "stage-entered", status: "processing", atMs: 12, durationMs: 12, stageId: STAGE.apiGateway, clusterId: CLUSTER.apiGateway, title: "Gateway routing request" },
    { id: "recovery:007:gateway-completed", type: "stage-completed", status: "success", atMs: 24, durationMs: 0, stageId: STAGE.apiGateway, clusterId: CLUSTER.apiGateway, title: "Gateway checks completed" },
    { id: "recovery:008:route-auth", type: "route-transmission", status: "processing", atMs: 26, durationMs: 2, routeId: ROUTE.gatewayToAuthentication, title: "Request transmitted to authentication" },
    { id: "recovery:009:auth-entered", type: "stage-entered", status: "processing", atMs: 28, durationMs: 38, stageId: STAGE.authentication, clusterId: CLUSTER.authentication, title: "Validating identity" },
    { id: "recovery:010:auth-completed", type: "stage-completed", status: "success", atMs: 66, durationMs: 0, stageId: STAGE.authentication, clusterId: CLUSTER.authentication, title: "Authentication approved" },
    { id: "recovery:011:route-core", type: "route-transmission", status: "processing", atMs: 68, durationMs: 2, routeId: ROUTE.authenticationToCore, title: "Authenticated request transmitted to core" },
    { id: "recovery:012:core-entered", type: "stage-entered", status: "processing", atMs: 70, durationMs: 12, stageId: STAGE.coreService, clusterId: CLUSTER.coreService, title: "Core service evaluating request" },
    { id: "recovery:013:route-cache", type: "route-transmission", status: "processing", atMs: 82, durationMs: 2, routeId: ROUTE.coreToCache, title: "Cache lookup requested" },
    { id: "recovery:014:cache-entered", type: "stage-entered", status: "processing", atMs: 84, durationMs: 8, stageId: STAGE.cache, clusterId: CLUSTER.cache, title: "Reading cache" },
    { id: "recovery:015:cache-completed", type: "stage-completed", status: "warning", atMs: 92, durationMs: 0, stageId: STAGE.cache, clusterId: CLUSTER.cache, title: "Cache miss", metrics: [{ id: "cache-hit", name: "Cache hit", value: false, status: "warning", trend: "down" }] },
    { id: "recovery:016:route-cache-core", type: "route-transmission", status: "processing", atMs: 94, durationMs: 2, routeId: ROUTE.cacheToCore, title: "Cache miss returned to core" },
    { id: "recovery:017:route-database", type: "route-transmission", status: "processing", atMs: 96, durationMs: 2, routeId: ROUTE.coreToDatabase, title: "Database fallback requested" },
    { id: "recovery:018:database-entered", type: "stage-entered", status: "processing", atMs: 98, durationMs: 180, stageId: STAGE.database, clusterId: CLUSTER.database, title: "Loading persistent context" },
    { id: "recovery:019:database-completed", type: "stage-completed", status: "success", atMs: 278, durationMs: 0, stageId: STAGE.database, clusterId: CLUSTER.database, title: "Persistent context loaded", metrics: [{ id: "database-latency", name: "Database latency", value: 180, unit: "ms", status: "neutral", trend: "stable" }] },
    { id: "recovery:020:route-database-core", type: "route-transmission", status: "processing", atMs: 280, durationMs: 2, routeId: ROUTE.databaseToCore, title: "Database context returned to core" },
    { id: "recovery:021:core-processing", type: "stage-processing", status: "processing", atMs: 282, durationMs: 6, stageId: STAGE.coreService, clusterId: CLUSTER.coreService, title: "Preparing external enrichment" },
    { id: "recovery:022:route-external", type: "route-transmission", status: "processing", atMs: 288, durationMs: 2, routeId: ROUTE.coreToExternal, title: "First external attempt transmitted" },
    { id: "recovery:023:external-entered", type: "stage-entered", status: "processing", atMs: 290, durationMs: 1200, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External inference attempt one" },
    { id: "recovery:024:timeout-warning", type: "warning-raised", status: "warning", atMs: 1488, durationMs: 0, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External timeout threshold reached", impact: { level: "medium", affectedClusterIds: [CLUSTER.externalAiApi], summary: "Only the external service boundary is affected." } },
    { id: "recovery:025:timeout-failure", type: "failure-raised", status: "error", atMs: 1490, durationMs: 0, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External request timed out", message: "The first external inference attempt exceeded 1200 ms.", metrics: [{ id: "first-attempt-timeout", name: "First attempt timeout", value: 1200, unit: "ms", status: "error", trend: "up" }], impact: { level: "high", affectedClusterIds: [CLUSTER.externalAiApi], summary: "Failure remains localized to the external AI/API cluster." }, metadata: { attempt: 1, localizedFailure: true } },
    { id: "recovery:026:retry-scheduled", type: "retry-scheduled", status: "recovering", atMs: 1492, durationMs: 500, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "Retry scheduled", retry: { attempt: 2, maximumAttempts: 2, delayMs: 500, reason: "External timeout" } },
    { id: "recovery:027:retry-started", type: "retry-started", status: "recovering", atMs: 1992, durationMs: 0, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "Retry started", retry: { attempt: 2, maximumAttempts: 2, delayMs: 500, reason: "External timeout" } },
    { id: "recovery:028:external-retrying", type: "stage-processing", status: "recovering", atMs: 1994, durationMs: 420, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External inference attempt two" },
    { id: "recovery:029:component-recovered", type: "component-recovered", status: "success", atMs: 2414, durationMs: 0, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External service recovered", metrics: [{ id: "second-attempt-latency", name: "Second attempt latency", value: 420, unit: "ms", status: "success", trend: "down" }], impact: { level: "none", affectedClusterIds: [CLUSTER.externalAiApi], summary: "External service resumed normal response delivery." } },
    { id: "recovery:030:external-completed", type: "stage-completed", status: "success", atMs: 2415, durationMs: 0, stageId: STAGE.externalAiApi, clusterId: CLUSTER.externalAiApi, title: "External inference completed after retry" },
    { id: "recovery:031:route-external-core", type: "route-transmission", status: "success", atMs: 2416, durationMs: 1, routeId: ROUTE.externalToCore, title: "Recovered result returned to core" },
    { id: "recovery:032:core-completed", type: "stage-completed", status: "success", atMs: 2417, durationMs: 0, stageId: STAGE.coreService, clusterId: CLUSTER.coreService, title: "Core processing completed" },
    { id: "recovery:033:route-response", type: "route-transmission", status: "processing", atMs: 2418, durationMs: 1, routeId: ROUTE.coreToResponse, title: "Result transmitted to response" },
    { id: "recovery:034:response-entered", type: "stage-entered", status: "processing", atMs: 2419, durationMs: 2, stageId: STAGE.response, clusterId: CLUSTER.response, title: "Assembling response" },
    { id: "recovery:035:response-sent", type: "response-sent", status: "success", atMs: 2421, durationMs: 0, stageId: STAGE.response, clusterId: CLUSTER.response, title: "Response sent", metrics: [{ id: "status-code", name: "Status code", value: 200, status: "success", trend: "stable" }, { id: "total-latency", name: "Total latency", value: 2422, unit: "ms", status: "warning", trend: "up" }] },
    { id: "recovery:036:response-completed", type: "stage-completed", status: "success", atMs: 2421.5, durationMs: 0, stageId: STAGE.response, clusterId: CLUSTER.response, title: "Response delivery completed" },
    { id: "recovery:037:execution-completed", type: "execution-completed", status: "success", atMs: 2422, durationMs: 0, title: "Execution recovered and completed" },
  ],
  outcome: {
    status: "recovered-success",
    totalDurationMs: 2422,
    processedStageCount: 8,
    warningCount: 1,
    failureCount: 1,
    retryCount: 1,
    failedClusterId: CLUSTER.externalAiApi,
    recoveredClusterId: CLUSTER.externalAiApi,
    summary: "External timeout remained localized, recovered on the second attempt, and returned HTTP 200.",
    metrics: [
      { id: "first-attempt-timeout", name: "First attempt timeout", value: 1200, unit: "ms", status: "error", trend: "up" },
      { id: "retry-delay", name: "Retry delay", value: 500, unit: "ms", status: "warning", trend: "stable" },
      { id: "second-attempt-latency", name: "Second attempt latency", value: 420, unit: "ms", status: "success", trend: "down" },
      { id: "retry-count", name: "Retry count", value: 1, status: "warning", trend: "stable" },
      { id: "status-code", name: "Status code", value: 200, status: "success", trend: "stable" },
    ],
  },
  playback: { recommendedDurationMs: 8200, minimumSpeed: 0.5, maximumSpeed: 2 },
});
