import type { NeuralCoreInspectionConfig } from "./neural-core-inspection.types";

export const DEFAULT_NEURAL_CORE_INSPECTION_CONFIG: NeuralCoreInspectionConfig = {
  enabled: false,
  camera: {
    allowRotate: true,
    allowZoom: true,
    allowPan: true,
    minimumDistance: 2.25,
    maximumDistance: 6.2,
    minimumPolarAngle: 0.35,
    maximumPolarAngle: Math.PI - 0.35,
    maximumPanDistance: 0.85,
    dampingFactor: 0.085,
    focusDistance: 3,
    focusTransitionSeconds: 0.55,
  },
  behavior: {
    pauseOnEnter: false,
    clearSelectionOnExit: true,
    focusSelectedCluster: true,
    dimUnrelatedContext: true,
    highlightRelatedConnections: true,
  },
  panel: {
    enabled: true,
    widthPx: 328,
    compactWidthPx: 286,
    maximumMetrics: 4,
    showDescription: true,
    showImpact: true,
    showRelationships: true,
  },
  visualDensity: {
    enabled: true,
    distance: {
      microMaximum: 3.15,
      mesoMaximum: 4.65,
    },
    macro: {
      baseConnectionOpacity: 1,
      ambientParticleOpacity: 1,
      unrelatedNodeOpacity: 1,
    },
    meso: {
      baseConnectionOpacity: 0.72,
      ambientParticleOpacity: 0.58,
      unrelatedNodeOpacity: 0.78,
    },
    micro: {
      baseConnectionOpacity: 0.38,
      ambientParticleOpacity: 0.12,
      unrelatedNodeOpacity: 0.34,
      relatedConnectionEmphasis: 1.12,
      internalConnectionEmphasis: 1.2,
    },
    visibility: {
      selected: {
        minimumNodeOpacity: 0.9,
        minimumConnectionOpacity: 0.54,
        minimumInternalConnectionOpacity: 0.62,
        minimumPulseOpacity: 0.88,
        emphasis: 1.08,
      },
      related: {
        minimumNodeOpacity: 0.62,
        minimumConnectionOpacity: 0.56,
        minimumPulseOpacity: 0.68,
        emphasis: 1.06,
      },
      context: {
        minimumNodeOpacity: 0.3,
        minimumConnectionOpacity: 0.26,
      },
      ambient: {
        minimumOpacity: 0.03,
        microOpacity: 0.065,
      },
      decorative: {
        minimumOpacity: 0.02,
        microOpacity: 0.045,
      },
    },
    relatedConnections: {
      minimumOpacity: 0.56,
      minimumThickness: 0.96,
      protagonistThicknessMultiplier: 1.22,
      relatedThicknessMultiplier: 1.08,
    },
    selectedClusterEnvelope: {
      enabled: false,
      maximumOpacity: 0.028,
      scaleMultiplier: 1.05,
      edgeSoftness: 0.72,
      pulseInfluence: 0.08,
    },
    decoration: {
      microArcOpacity: 0.08,
      microBaseOpacity: 0.12,
      microGlobalGlowOpacity: 0.32,
    },
    transitionDamping: 8.5,
  },
  cameraRendering: {
    enabled: true,
    distance: {
      near: 2.5,
      far: 6.2,
    },
    nodes: {
      minimumScreenSize: 1.15,
      maximumScreenSize: 12,
      selectedMaximumScreenSize: 12.5,
      nearDistanceScale: 0.84,
      farDistanceScale: 1.16,
      nearExposureCompensation: 0.72,
      farExposureCompensation: 1.08,
      additiveCompensation: 0.9,
    },
    connections: {
      minimumNearOpacity: 0.032,
      minimumFarOpacity: 0.072,
      minimumNearThickness: 0.72,
      minimumFarThickness: 0.94,
      selectedThicknessMultiplier: 1.08,
      relatedThicknessMultiplier: 1.04,
      farContrastBoost: 1.12,
    },
    pulses: {
      minimumOpacity: 0.1,
      nearDistanceScale: 0.9,
      farDistanceScale: 1.1,
      nearExposureCompensation: 0.78,
      farExposureCompensation: 1.06,
    },
    fog: {
      preserveFunctionalTopology: true,
      dynamicEnvironmentFog: true,
      farMargin: 2.2,
    },
    transitionDamping: 8,
  },
};
